Restrict Keras to <v2.3.0
Both Keras v2.3.0 and v2.3.1 on Traverse (and at least the latter on
TigerGPU) die with:

WARNING:tensorflow:From
/home/kfelker/.conda/envs/frnn/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630:
calling BaseReso\
urceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops)
with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Printing out pre_rnn model...
Traceback (most recent call last):
  File "mpi_learn.py", line 111, in <module>
      shot_list_test=shot_list_test)

  File
  "/home/kfelker/.conda/envs/frnn/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py",
  line 1229, in __imul__
      raise RuntimeError("Variable *= value not supported. Use "
      RuntimeError: Variable *= value not supported. Use
      `var.assign(var * value)` to modify the variable or `var = var *
      value` to get a new Tensor object.

Incompatibility likely fixed in TF >= v2.0 and/or TF's internal Keras
https://github.com/tensorflow/tensorflow/issues/27829

Re-check this after moving to TensorFlow's internal Keras in #43