Pass allow_pickle=True to final np.savez() call in MPI script
(even though option is not documented for this function, and deprecation
should not cause an error until v1.18.0, which has not been released)
Prevents the following error with numpy v1.16.2, tf v1.3.0:

/home/kfelker/.conda/envs/frnn-tf1.3.0/lib/python3.6/site-packages/numpy/lib/npyio.py:750:
FutureWarning: Object arrays will not be saved by default in the future
because `allow_pickle` will default to False. You should add
`allow_pickle=True` explicitly to eliminate this
warning. pickle_kwargs=pickle_kwargs)

 Traceback (most recent call last):
 File "./mpi_learn.py", line 151, in <module>
 shot_list_test=shot_list_test, conf=conf)
 File
"/home/kfelker/.conda/envs/frnn-tf1.3.0/lib/python3.6/site-packages/numpy/lib/npyio.py",
line 639, in savez
_savez(file, args, kwds, False, allow_pickle=_allow_pickle)
File "/home/kfelker/.conda/envs/frnn-tf1.3.0/lib/python3.6/site-packages/numpy/lib/npyio.py",
 line 750, in _savez
 pickle_kwargs=pickle_kwargs)
 File
 "/home/kfelker/.conda/envs/frnn-tf1.3.0/lib/python3.6/site-packages/numpy/lib/format.py",
 line 637, in write_array
 raise ValueError("Object arrays cannot be saved when "

ValueError: Object arrays cannot be saved when allow_pickle=False